export const SET_INFO_CURRENT_USER = "SET_INFO_CURRENT_USER";
export const OPEN_COLLAPSED_ADMIN = "OPEN_COLLAPSED_ADMIN";
export const EXPEND_COLLAPSED_ADMIN = "EXPEND_COLLAPSED_ADMIN";
export const LIST_USERS = "LIST_USERS";

